import java.util.ArrayList;
ArrayList<String> boodschappen = new ArrayList<String>();
boodschappen.add("melk");
boodschappen.add("brood");
boodschappen.add("water");
boodschappen.add("koek");
boodschappen.add("pindakaas");
boodschappen.add("wortel");
boodschappen.add("vlees");
boodschappen.get(2);
boodschappen.remove(1);
boodschappen.size();
println (boodschappen.get(2));
println (boodschappen.size());
